### ISSUE TITLE
Logging Mbean is not working correctly. Unable to change log levels or retrieve existing log levels

### ISSUE THREAD

**Issue by vishalmodak** [kenwdelong/jmx-console#1]
Hi..

I am using version 2.0.0 of jmx-console. I am testing this with SpringBoot 1.3.0.M5. 
I am able to bring up the JMX console successfully on /admin/jmx.
However, when I try to query for existing log level of one of my loggers. I just get a "Success" string.
When I try to change the log level of an existing logger, it fails.

My loggers are setup in logback.xml.

Also the LoggerNames in Logging bean doesnt show readable logger names.

Any help would be greatly appreciated.

Vishal

**Comment by kenwdelong** [comment]
The LogConfigurer MBean only works for Log4J - the source uses Log4J classes.
If you are using LogBack, you don't need a special MBean, it's built into Logback. Just add  `<jmxConfigurator />` to your logback.xml and you'll see the MBean exported.  And they do have a "setLoggerLevel()" method - in fact, I just used it today!

Glad you are finding the console useful!
